name: Deploy Trunks to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p $VPS_SSH_PORT $VPS_USER@$VPS_HOST "
          
            if [ ! -d '/home/ubuntu/Trunks' ]; then
              GIT_SSH_COMMAND='ssh -i /root/.ssh/trunks/deploy-trunks' git clone git@github.com:AkiraaCorp/Trunks.git /home/ubuntu/Trunks
            else
              cd /home/ubuntu/Trunks && GIT_SSH_COMMAND='ssh -i /root/.ssh/trunks/deploy-trunks' git pull origin main
            fi
            cd /home/ubuntu/Trunks

            cat > .env <<EOL
          DATABASE_URL=postgresql://postgres:${{ secrets.DB_PASSWORD }}@localhost:5432/sightbet
          RPC_ENDPOINT=https://starknet-sepolia.blastapi.io/a1c45f16-3f71-48f5-aaeb-925f5954e8a4
          EOL
            rustup default stable
            pm2 describe trunks-cron > /dev/null && pm2 stop trunks-cron || echo 'Process not running'
            cargo build --release
            pm2 start target/release/trunks --name trunks-cron --no-autorestart
          "
        env:
          VPS_HOST: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USERNAME }}
          VPS_SSH_PORT: ${{ secrets.VPS_SSH_PORT }}